spring:
  datasource:
    url: jdbc:mysql://192.168.0.128:3309/higt_concurrence?useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false


#  ================ jpa ================
#  配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
#  jpa:
#        hibernate:
#          ddl-auto: update
#    show-sql: true

  redis:
    database: 0       # Redis数据库索引（默认为0）
    host: 192.168.0.128   # Redis服务器地址
    port: 6379        # Redis服务器连接端口
    #password:        # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10    # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）

# ================  mybatis - plus ================
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0