logging:
  level:
    root: info
    own.stu.springboot.logging: error
  pattern:
    console: ==| %d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n

server:
  port: 8090

spring:
  profiles:
    active: dev
