spring:
  redis:
#  单节点
    database: 1           #Redis数据库索引（默认为0）
    host: 127.0.0.1    # Redis服务器地址
    port: 6379            # Redis服务器连接端口
    password:             # Redis服务器连接密码（默认为空）
    timeout: 10000ms      # 连接超时时间（毫秒）

    #redis哨兵模式
#    sentinel:
#      master: rmaster
#      nodes: 172.16.2.163:26319