spring:
  redis:
    database: 1           #Redis数据库索引（默认为0）
    host: 172.16.2.163    # Redis服务器地址
    port: 6319            # Redis服务器连接端口
    password:             # Redis服务器连接密码（默认为空）
    timeout: 10000ms      # 连接超时时间（毫秒）

    jedis:
      pool:
        max-active: 500   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 40      # 连接池中的最大空闲连接
        min-idle: 8       # 连接池中的最小空闲连接
